select
    transaction_hash,
    transaction_index,
    from_address,
    to_address,
    value,
    input,
    output,
    trace_type,
    call_type,
    reward_type,
    gas,
    gas_used,
    subtraces,
    trace_address,
    error,
    status,
    datetime(block_timestamp) AS block_timestamp,
    block_number,
    block_hash,
    trace_id
from `bigquery-public-data.crypto_ethereum.traces`